annotations:
  category: CMS
apiVersion: v2
appVersion: 4.24.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: A simple, powerful publishing platform that allows you to share your stories with the world
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/ghost
icon: https://bitnami.com/assets/stacks/ghost/img/ghost-stack-220x234.png
keywords:
  - ghost
  - blog
  - http
  - web
  - application
  - nodejs
  - javascript
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
  - email: nikita@tokarch.uk
    name: Nikita Tokarchuk
name: ghost
sources:
  - https://github.com/mainnika/ghost-docker
  - https://www.ghost.org/
version: 15.1.6
